services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-storage-frontend-runtime
    ports:
      - "8083:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: production
